global:
  resolve_timeout: 5m
  smtp_smarthost: 'smtp.gmail.com:587'
  smtp_from: '<your-email-here>'
  smtp_auth_username: '<your-email-here>'
  smtp_auth_password: '<your-app-password-here>'
  smtp_require_tls: true

route:
  receiver: "email-notifications"
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 4h

receivers:
  - name: "email-notifications"
    email_configs:
      - to: '<recipient-email-here>'
        send_resolved: true
