events {}

http {
    server {
        listen 80;

        root /usr/share/nginx/html;
        index index.html;

        location / {
            try_files $uri $uri/ =404;
        }

        # Stub status endpoint for Prometheus
        location /stub_status {
            stub_status;
        }
    }
}
